/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.codigo.telas;

import cadatro.TelaCadastro;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        scrollPane1 = new java.awt.ScrollPane();
        irCadastro = new javax.swing.JButton();
        irLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Menu");
        getContentPane().setLayout(null);

        irCadastro.setFont(new java.awt.Font("Consola Mono", 0, 12)); // NOI18N
        irCadastro.setText("Cadastro");
        irCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(irCadastro);
        irCadastro.setBounds(460, 570, 170, 25);

        irLogin.setFont(new java.awt.Font("Consola Mono", 0, 12)); // NOI18N
        irLogin.setText("Login");
        irLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irLoginActionPerformed(evt);
            }
        });
        getContentPane().add(irLogin);
        irLogin.setBounds(660, 570, 110, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1000057448.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1290, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irCadastroActionPerformed
        // TODO add your handling code here:
        TelaCadastro tela = new TelaCadastro();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_irCadastroActionPerformed

    private void irLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irLoginActionPerformed
        TelaLogins tela = new TelaLogins();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_irLoginActionPerformed



    /**int largura = (int) (jLabel1.getWidth() * 5);  // 20% maior
    int altura  = (int) (jLabel1.getHeight() * 5); // 20% maior

    Image img = icon.getImage().getScaledInstance(
            largura,
            altura,
            Image.SCALE_SMOOTH
    );

    jLabel1.setIcon(new ImageIcon(img));*/


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }
        //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton irCadastro;
    private javax.swing.JButton irLogin;
    private javax.swing.JLabel jLabel2;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
